[package]
name = "elogind-usersvd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
elogind-usersv-core = { path = "../crates/core" }
elogind-usersv-protocol = { path = "../crates/protocol" }
env_logger.workspace = true
futures-util.workspace = true
libc.workspace = true
log.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "signal", "sync", "time"] }
zbus.workspace = true
